# Generated by Django 2.2.5 on 2019-11-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_auto_20191112_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shampoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
    ]
